/*
 * IOTGpsSettings.h
 *
 *  Created on: 1 mar 2022
 *      Author: migue_t0ro5dr
 */

#ifndef IOTGPSSETTINGS_H_
#define IOTGPSSETTINGS_H_

#include <Timezone.h>

enum PUBLISH_POSITION_SEC_INTERVAL {
	NO_PUBLISH_POSITION_INTERVAL = 0,
	PUBLISH_POSITION_20_SEC_INTERVAL = 20,
	PUBLISH_POSITION_1_MINUTE_INTERVAL = 60,
	PUBLISH_POSITION_2_MINUTES_INTERVAL = 120,
	PUBLISH_POSITION_5_MINUTES_INTERVAL = 300,
	PUBLISH_POSITION_10_MINUTES_INTERVAL = 600,
	PUBLISH_POSITION_20_MINUTES_INTERVAL = 1200,
	PUBLISH_POSITION_30_MINUTES_INTERVAL = 1800,
	PUBLISH_POSITION_1_HOUR_INTERVAL = 3600,
	PUBLISH_POSITION_2_HOURS_INTERVAL = 7200,
	PUBLISH_POSITION_5_HOURS_INTERVAL = 18000,
	PUBLISH_POSITION_10_HOURS_INTERVAL = 36000,
	PUBLISH_POSITION_24_HOURS_INTERVAL = 86400
};


class IOTGpsSettings {
public:
	IOTGpsSettings(PUBLISH_POSITION_SEC_INTERVAL publishPositionInterval, LOCAL_TIMEZONE localTimeZone);
	bool isReachedPublishInterval(unsigned long timePassedMillis);
	long toLocalEpochTime(long epochTime);
	PUBLISH_POSITION_SEC_INTERVAL getPublishPositionInterval();
private:
	PUBLISH_POSITION_SEC_INTERVAL publishPositionInterval;
	Timezone localTimeZone;
};

#endif /* IOTGPSSETTINGS_H_ */
